### PR TITLE
Spring4 hibernate4 migration

### PR DESCRIPTION
**Pull request by wjase**
Bumped versions of spring and hibernate. 
Refactored transaction behaviour.
Started work on converting xml config to java config.
Added dao/config test

### CODE REVIEW

**Comment by stevespringett** [comment]
Jason,
Thanks for the pull request. Excellent work! Is there anything more left to do for this? Also, there seems to be a merge conflict.

**Comment by wjase** [comment]
Hi Steve,

Yup, I'm nearly done converting to Spring java config and eliminating 
the need for web.xml.

How do I see the merge conflict to resolve? (This is the first time I've 
done a pull request on github)

After that I'm hoping to do something similar to a spike we did in our 
company's codeblitz where we created an api to populate the component 
list from a maven plugin...

I noted in the presentation you did that you were hoping to implement an 
API to populate the compnents - that's kind of what we did, but it was a 
bit hacky in a 2 day coding frenzy - I'd like to apply a more considered 
approach once I've fixed up a couple of these config and code 
consistency issues...

Let me know if you want to chat further - or if other folk are already 
ploughing ahead in this area...

Cheers,

Jason Wraxall

**Comment by wjase** [comment]
Hi Steve, I'm trying to see conflicts - but don't see any. did a git pull + git merge but it says I'm up to date?

**Comment by stevespringett** [comment]
Let's merge this request when you're complete and I'll add the Last-Modifier header patch that another user contributed after the fact.

I had just started on rewriting much of the API (and including importing of Dependency-Check reports) when this request came in. This is such a major (but good) change, that I'll have to revisit the API when this request is merged in. Let's chat about that functionality in Ticket #4

**Comment by stevespringett** [comment]
Is there any more work to do on this pull request? If not, I'll go ahead and merge.

**Comment by wjase** [comment]
Mostly done now. Need to fix up where the log is written using spring boot.
Would be interested for folks to have a play in case I've inadvertently changed some behaviour

**Comment by stevespringett** [comment]
Jason, free free to add yourself as a developer in the pom. Would you like to be added to https://www.owasp.org/index.php/OWASP_Dependency_Track_Project#tab=Acknowledgements ?

**Comment by stevespringett** [comment]
Most functionality no longer works - especially from a clean database. Transactions are missing which are absolutely essential, and the complexity of hibernate session handling is unnecessary. I'm going to rip out most of the refactoring of hibernate query changes as most of the changes have introduced defects.

**Comment by wjase** [comment]
Hi Steve,

Have seen a similar issue in the last few days with spring boot and jsp.
Mvn spring-boot:run works but running the jar does not.

I'll Try and get it sorted as soon as I can.

2 options I know of.
1) keep jsp and do some jiggery pokery to make Spring Boot Happy
2) Convert to Thymeleaf

I'm inclined to keep jsp until I've sorted out the persistence issues 
and then think about what you'd like me to do.
I've just converted a mammoth internal web app at tyro from war to 
executable jar with jsps and it was quite a slog - but I should be able 
to leverage my lessons learned and scars obtained to make this one faster...



Cheers,

Jason

----- Reply message -----

**Pull request merged**
